version: "3"

# Define the services that will be run in the containers
services:
  # The frontend-workshop service is built from the Dockerfile located in the ./apps/frontend-workshop directory
  storybook:
    build:
      context: .
      dockerfile: apps/frontend-workshop/Dockerfile
      cache_from:
        - turborepo-template-frontend-workshop:latest
      cache_to:
        - type=local,dest=/tmp/docker-cache
    ports:
      - 6006:80
    networks:
      - storybook_network

  # The frontend-workshop-test-runner service is built from the Dockerfile located in the ./apps/frontend-workshop directory
  storybook-test-runner:
    build:
      context: .
      dockerfile: apps/frontend-workshop/Dockerfile.test-runner
      cache_from:
        - turborepo-template-frontend-workshop-test-runner:latest
      cache_to:
        - type=local,dest=/tmp/docker-cache
    networks:
      - storybook_network
    depends_on:
      - storybook
    environment:
      CI: true
      TARGET_URL: http://storybook:80

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  storybook_network:
    external: true